[nix]
channel = "stable-22_11"

[deployment]
run = ["sh", "-c", "node ."]

[[ports]]
localPort = 1405
externalPort = 80

[pkgs]
deps = [
    pkgs.nodejs-16_x,
    pkgs.nodejs-16_x,
    pkgs.nodejs-16_x,
    pkgs.libwebp,
    pkgs.nodePackages.typescript,
    pkgs.libuuid,
    pkgs.ffmpeg,
    pkgs.imagemagick,
    pkgs.wget,
    pkgs.git,
    pkgs.nodePackages.pm2
]
env = {
    LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [ pkgs.libuuid ];
}
